/*
 * FancyBox - jQuery Plugin
 * simple and fancy lightbox alternative
 *
 * Copyright (c) 2009 Janis Skarnelis
 * Examples and documentation at: http://fancybox.net
 * 
 * Version: 1.2.6 (16/11/2009)
 * Requires: jQuery v1.3+
 * 
 * Code changed by AJAX-ZOOM
 *
 * Dual licensed under the MIT and GPL licenses:
 *   http://www.opensource.org/licenses/mit-license.php
 *   http://www.gnu.org/licenses/gpl.html
 */

 var axZmBrowserMigrate=function(){var a,e,b,d;a=window.navigator.userAgent;a=a.toLowerCase();e=/(opr)[\/]([\w.]+)/.exec(a)||/(chrome)[ \/]([\w.]+)/.exec(a)||/(version)[ \/]([\w.]+).*(safari)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||0<=a.indexOf("trident")&&/(rv)(?::| )([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];b=/(ipad)/.exec(a)||/(iphone)/.exec(a)||/(android)/.exec(a)||
/(windows phone)/.exec(a)||/(win)/.exec(a)||/(mac)/.exec(a)||/(linux)/.exec(a)||/(cros)/i.exec(a)||[];a=e[3]||e[1]||"";e=e[2]||"0";b=b[0]||"";d={};a&&(d[a]=!0,d.version=e,d.versionNumber=parseInt(e));b&&(d[b]=!0);if(d.android||d.ipad||d.iphone||d["windows phone"])d.mobile=!0;if(d.cros||d.mac||d.linux||d.win)d.desktop=!0;if(d.chrome||d.opr||d.safari)d.webkit=!0;d.rv&&(a="msie",d.msie=!0);d.opr&&(a="opera",d.opera=!0);d.safari&&d.android&&(a="android",d.android=!0);d.name=a;d.platform=b;$.browser?$.extend($.browser,
d):$.browser=d;$.browser.mozilla&&$.browser.msie&&delete $.browser.mozilla;$.support||($.support={});$.support.boxModel="CSS1Compat"===document.compatMode};axZmBrowserMigrate();
(function(a){a.fn.fixPNG=function(){return this.each(function(){var b=a(this).css("backgroundImage");b.match(/^url\(["']?(.*\.png)["']?\)$/i)&&(b=RegExp.$1,a(this).css({backgroundImage:"none",filter:"progid:DXImageTransform.Microsoft.AlphaImageLoader(enabled=true, sizingMethod="+("no-repeat"==a(this).css("backgroundRepeat")?"crop":"scale")+", src='"+b+"')"}).each(function(){var b=a(this).css("position");"absolute"!=b&&"relative"!=b&&a(this).css("position","relative")}))})};var e,b,d=!1,g=new Image,
n,k=1,r=/\.(jpg|gif|png|bmp|jpeg)(.*)?$/i,t=null,m=a.browser.msie&&6==a.browser.version.substr(0,1)&&!window.XMLHttpRequest,u=m||a.browser.msie&&7==a.browser.version.substr(0,1);a.fn.fancybox=function(c){function f(){a("#fancy_right, #fancy_left, #fancy_close, #fancy_title").hide();var c=b.itemArray[b.itemCurrent].href;if(c.match("iframe")||0<=e.className.indexOf("iframe"))a.fn.fancybox.showLoading(),p('<iframe id="fancy_frame" onload="jQuery.fn.fancybox.showIframe()" name="fancy_iframe'+Math.round(1E3*
Math.random())+'" frameborder="0" hspace="0" src="'+c+'"></iframe>',b.frameWidth,b.frameHeight);else if(c.match(/#/)){var d=window.location.href.split("#")[0],d=c.replace(d,""),d=d.substr(d.indexOf("#"));p('<div id="fancy_div">'+a(d).html()+"</div>",b.frameWidth,b.frameHeight)}else c.match(r)&&!c.match(/zoomData/)?(g=new Image,g.src=c,g.complete?v():(a.fn.fancybox.showLoading(),a(g).unbind().bind("load",function(){a("#fancy_loading").hide();v()}))):(a.fn.fancybox.showLoading(),a.get(c,function(b){a("#fancy_loading").hide();
tempData=b.replace(/<script{1}.*>*<\/script>/i,"");a("<DIV />").attr("id","fancyTemp").css({display:"none",minWidth:150,minHeight:150}).html(tempData).appendTo("body");var c=a("#fancyTemp").outerWidth(),w=a("#fancyTemp").outerHeight();a("#fancyTemp").remove();p('<div id="fancy_ajax">'+b+"</div>",c,w)}))}function v(){var c=g.width,d=g.height,f=2*b.padding+40,h=2*b.padding+60,e=a.fn.fancybox.getViewport();b.imageScale&&(c>e[0]-f||d>e[1]-h)&&(f=Math.min(Math.min(e[0]-f,c)/c,Math.min(e[1]-h,d)/d),c=Math.round(f*
c),d=Math.round(f*d));p('<img alt="" id="fancy_img" src="'+g.src+'" />',c,d)}function x(){if(b.itemArray.length-1>b.itemCurrent){var a=b.itemArray[b.itemCurrent+1].href||!1;a&&a.match(r)&&!a.match(/zoomData/)&&(objNext=new Image,objNext.src=a)}0<b.itemCurrent&&(a=b.itemArray[b.itemCurrent-1].href||!1)&&a.match(r)&&!a.match(/zoomData/)&&(objNext=new Image,objNext.src=a)}function p(c,f,e){d=!0;var h=b.padding;if(u||t)a("#fancy_content")[0].style.removeExpression("height"),a("#fancy_content")[0].style.removeExpression("width");
if(0<h){if(f+=2*h,e+=2*h,a("#fancy_content").css({top:h+"px",right:h+"px",bottom:h+"px",left:h+"px",width:"auto",height:"auto"}),u||t)a("#fancy_content")[0].style.setExpression("height","(this.parentNode.clientHeight - "+2*h+")"),a("#fancy_content")[0].style.setExpression("width","(this.parentNode.clientWidth - "+2*h+")")}else a("#fancy_content").css({top:0,right:0,bottom:0,left:0,width:"100%",height:"100%"});if(a("#fancy_outer").is(":visible")&&f==a("#fancy_outer").width()&&e==a("#fancy_outer").height())a("#fancy_content").fadeOut("fast",
function(){a("#fancy_content").empty().append(a(c)).fadeIn("normal",function(){q()})});else{var h=a.fn.fancybox.getViewport(),g=e+60>h[1]?h[3]:h[3]+Math.round(.5*(h[1]-e-60)),k={left:f+40>h[0]?h[2]:h[2]+Math.round(.5*(h[0]-f-40)),top:g,width:f+"px",height:e+"px"};a("#fancy_outer").is(":visible")?a("#fancy_content").fadeOut("normal",function(){a("#fancy_content").empty();a("#fancy_outer").animate(k,b.zoomSpeedChange,b.easingChange,function(){a("#fancy_content").append(a(c)).fadeIn("normal",function(){q()})})}):
0<b.zoomSpeedIn&&void 0!==b.itemArray[b.itemCurrent].orig?(a("#fancy_content").empty().append(a(c)),f=b.itemArray[b.itemCurrent].orig,e=a.fn.fancybox.getPosition(f),a("#fancy_outer").css({left:e.left-20-b.padding+"px",top:e.top-20-b.padding+"px",width:a(f).width()+2*b.padding,height:a(f).height()+2*b.padding}),b.zoomOpacity&&(k.opacity="show"),a("#fancy_outer").animate(k,b.zoomSpeedIn,b.easingIn,function(){q()})):(a("#fancy_content").hide().empty().append(a(c)).show(),a("#fancy_outer").css(k).fadeIn("normal",
function(){q()}))}}function n(){0!==b.itemCurrent&&(a("#fancy_left, #fancy_left_ico").unbind().bind("click",function(a){a.stopPropagation();b.itemCurrent--;f();return!1}),a("#fancy_left").show());b.itemCurrent!=b.itemArray.length-1&&(a("#fancy_right, #fancy_right_ico").unbind().bind("click",function(a){a.stopPropagation();b.itemCurrent++;f();return!1}),a("#fancy_right").show())}function q(){a.browser.msie&&(a("#fancy_content")[0].style.removeAttribute("filter"),a("#fancy_outer")[0].style.removeAttribute("filter"));
n();x();a(document).bind("keydown.fb",function(c){27==c.keyCode&&b.enableEscapeButton?a.fn.fancybox.close():37==c.keyCode&&0!==b.itemCurrent?(a(document).unbind("keydown.fb"),b.itemCurrent--,f()):39==c.keyCode&&b.itemCurrent!=b.itemArray.length-1&&(a(document).unbind("keydown.fb"),b.itemCurrent++,f())});b.hideOnContentClick&&a("#fancy_content").click(a.fn.fancybox.close);b.overlayShow&&b.hideOnOverlayClick&&a("#fancy_overlay").bind("click",a.fn.fancybox.close);b.showCloseButton&&a("#fancy_close").bind("click",
a.fn.fancybox.close).show();if("undefined"!==typeof b.itemArray[b.itemCurrent].title&&0<b.itemArray[b.itemCurrent].title.length){var c=a("#fancy_outer").position();a("#fancy_title div").text(b.itemArray[b.itemCurrent].title).html();a("#fancy_title").css({top:c.top+a("#fancy_outer").outerHeight()-32,left:c.left+(.5*a("#fancy_outer").outerWidth()-.5*a("#fancy_title").width())}).show()}b.overlayShow&&m&&a("embed, object, select",a("#fancy_content")).css("visibility","visible");a.isFunction(b.callbackOnShow)&&
b.callbackOnShow(b.itemArray[b.itemCurrent]);a.browser.msie&&(a("#fancy_outer")[0].style.removeAttribute("filter"),a("#fancy_content")[0].style.removeAttribute("filter"));d=!1}var k=a.extend({},a.fn.fancybox.defaults,c),y=this;return this.unbind("click.fb").bind("click.fb",function(){e=this;b=a.extend({},k);if(!d){a.isFunction(b.callbackOnStart)&&b.callbackOnStart();b.itemArray=[];b.itemCurrent=0;if(0<k.itemArray.length)b.itemArray=k.itemArray;else{var c={};if(e.rel&&""!=e.rel)for(var g=a(y).filter("a[rel="+
e.rel+"]"),l=0;l<g.length;l++){c={href:g[l].href,title:g[l].title};a(g[l]).children("img:first").length?c.orig=a(g[l]).children("img:first"):c.orig=a(g[l]);if(""==c.title||"undefined"==typeof c.title)c.title=c.orig.attr("alt");b.itemArray.push(c)}else{c={href:e.href,title:e.title};a(e).children("img:first").length?c.orig=a(e).children("img:first"):c.orig=a(e);if(""==c.title||"undefined"==typeof c.title)c.title=c.orig.attr("alt");b.itemArray.push(c)}}for(;b.itemArray[b.itemCurrent].href!=e.href;)b.itemCurrent++;
b.overlayShow&&(m&&(a("embed, object, select").css("visibility","hidden"),a("#fancy_overlay").css("height",a(document).height())),a("#fancy_overlay").css({"background-color":b.overlayColor,opacity:b.overlayOpacity}).show());a(window).bind("resize.fb scroll.fb",a.fn.fancybox.scrollBox);f()}return!1})};a.fn.fancybox.scrollBox=function(){var c=a.fn.fancybox.getViewport();if(b.centerOnScroll&&a("#fancy_outer").is(":visible")){var d=a("#fancy_outer").outerWidth(),e=a("#fancy_outer").outerHeight(),g={top:e>
c[1]?c[3]:c[3]+Math.round(.5*(c[1]-e)),left:d>c[0]?c[2]:c[2]+Math.round(.5*(c[0]-d))};a("#fancy_outer").css(g);a("#fancy_title").css({top:g.top+e-32,left:g.left+(.5*d-.5*a("#fancy_title").width())})}m&&a("#fancy_overlay").is(":visible")&&a("#fancy_overlay").css({height:a(document).height()});a("#fancy_loading").is(":visible")&&a("#fancy_loading").css({left:.5*(c[0]-40)+c[2],top:.5*(c[1]-40)+c[3]})};a.fn.fancybox.getNumeric=function(c,b){return parseInt(a.css(c.jquery?c[0]:c,b,!0))||0};a.fn.fancybox.getPosition=
function(c){var b=c.offset();b.top+=a.fn.fancybox.getNumeric(c,"paddingTop");b.top+=a.fn.fancybox.getNumeric(c,"borderTopWidth");b.left+=a.fn.fancybox.getNumeric(c,"paddingLeft");b.left+=a.fn.fancybox.getNumeric(c,"borderLeftWidth");return b};a.fn.fancybox.showIframe=function(){a("#fancy_loading").hide();a("#fancy_frame").show()};a.fn.fancybox.getViewport=function(){return[a(window).width(),a(window).height(),a(document).scrollLeft(),a(document).scrollTop()]};a.fn.fancybox.animateLoading=function(){a("#fancy_loading").is(":visible")?
(a("#fancy_loading > div").css("top",-40*k+"px"),k=(k+1)%12):clearInterval(n)};a.fn.fancybox.showLoading=function(){clearInterval(n);var b=a.fn.fancybox.getViewport();a("#fancy_loading").css({left:.5*(b[0]-40)+b[2],top:.5*(b[1]-40)+b[3]}).show();a("#fancy_loading").bind("click",a.fn.fancybox.close);n=setInterval(a.fn.fancybox.animateLoading,66)};a.fn.fancybox.close=function(){d=!0;a(g).unbind();a(document).unbind("keydown.fb");a(window).unbind("resize.fb scroll.fb");a("#fancy_overlay, #fancy_content, #fancy_close").unbind();
a("#fancy_close, #fancy_loading, #fancy_left, #fancy_right, #fancy_title").hide();__cleanup=function(){a("#fancy_overlay").is(":visible")&&a("#fancy_overlay").fadeOut("fast");a("#fancy_content").empty();b.centerOnScroll&&a(window).unbind("resize.fb scroll.fb");m&&a("embed, object, select").css("visibility","visible");a.isFunction(b.callbackOnClose)&&b.callbackOnClose();d=!1};if(!1!==a("#fancy_outer").is(":visible"))if(0<b.zoomSpeedOut&&void 0!==b.itemArray[b.itemCurrent].orig){var c=b.itemArray[b.itemCurrent].orig,
e=a.fn.fancybox.getPosition(c),c={left:e.left-20-b.padding+"px",top:e.top-20-b.padding+"px",width:a(c).width()+2*b.padding,height:a(c).height()+2*b.padding};b.zoomOpacity&&(c.opacity="hide");a("#fancy_outer").stop(!1,!0).animate(c,b.zoomSpeedOut,b.easingOut,__cleanup)}else a("#fancy_outer").stop(!1,!0).fadeOut("fast",__cleanup);else __cleanup();return!1};a.fn.fancybox.build=function(){var b;b='<div id="fancy_overlay"></div><div id="fancy_loading"><div></div></div>';b+='<div id="fancy_outer">';b+=
'<div id="fancy_inner">';b+='<div id="fancy_close"></div>';b+='<div id="fancy_bg"><div class="fancy_bg" id="fancy_bg_n"></div><div class="fancy_bg" id="fancy_bg_ne"></div><div class="fancy_bg" id="fancy_bg_e"></div><div class="fancy_bg" id="fancy_bg_se"></div><div class="fancy_bg" id="fancy_bg_s"></div><div class="fancy_bg" id="fancy_bg_sw"></div><div class="fancy_bg" id="fancy_bg_w"></div><div class="fancy_bg" id="fancy_bg_nw"></div></div>';b+='<a href="javascript:;" id="fancy_left"><span class="fancy_ico" id="fancy_left_ico"></span></a><a href="javascript:;" id="fancy_right"><span class="fancy_ico" id="fancy_right_ico"></span></a>';
b+='<div id="fancy_content"></div>';b+="</div>";b+="</div>";b+='<div id="fancy_title"></div>';a(b).appendTo("body");a('<table cellspacing="0" cellpadding="0" border="0"><tr><td class="fancy_title" id="fancy_title_left"></td><td class="fancy_title" id="fancy_title_main"><div></div></td><td class="fancy_title" id="fancy_title_right"></td></tr></table>').appendTo("#fancy_title");a.browser.msie&&a(".fancy_bg").fixPNG();m&&(a("div#fancy_overlay").css("position","absolute"),a("#fancy_loading div, #fancy_close, .fancy_title, .fancy_ico").fixPNG(),
a("#fancy_inner").prepend('<iframe id="fancy_bigIframe" src="javascript:false;" scrolling="no" frameborder="0"></iframe>'),b=a("#fancy_bigIframe")[0].contentWindow.document,b.open(),b.close())};a.fn.fancybox.defaults={padding:10,imageScale:!0,zoomOpacity:!0,zoomSpeedIn:0,zoomSpeedOut:0,zoomSpeedChange:300,easingIn:"swing",easingOut:"swing",easingChange:"swing",frameWidth:560,frameHeight:340,overlayShow:!0,overlayOpacity:.3,overlayColor:"#666",enableEscapeButton:!0,showCloseButton:!0,hideOnOverlayClick:!0,
hideOnContentClick:!0,centerOnScroll:!0,itemArray:[],callbackOnStart:null,callbackOnShow:null,callbackOnClose:null};a(document).ready(function(){t=a.browser.msie&&!a.boxModel;1>a("#fancy_outer").length&&a.fn.fancybox.build()})})(jQuery);