<div id="slider" class="nivoSlider">
    <img src="http://edu.igf.com.vn/images/slide/khaigiang06.jpg" width="730" alt="" title="HÌNH ẢNH LỚP HỌC BUỔI KHAI GIẢNG TUẦN TƯ VẤN & HỌC THỬ MIỄN PHÍ.<br><a href='http://edu.igf.com.vn/index.php?com=contents&viewtype=article&item=166'>Xem thêm...<a/>"/>
    <img src="http://edu.igf.com.vn/images/slide/khaigiang01.jpg" width="730" alt="" title="Tuần học thử MIỄN PHÍ. Chúng tôi sẽ tiếp tục nhận thông tin <a href='?com=register'>đăng ký</a> của các bạn. Vui lòng <a href='?com=register'>đăng ký</a> với chúng tôi trực tiếp tại 173 Xuân Thủy, qua tư vấn tuyển sinh hoặc trên Website"/>
    <img src="http://edu.igf.com.vn/images/slide/khaigiang03.jpg" width="730" alt="" title="HÌNH ẢNH LỚP HỌC BUỔI KHAI GIẢNG TUẦN TƯ VẤN & HỌC THỬ MIỄN PHÍ.<br><a href='http://edu.igf.com.vn/index.php?com=contents&viewtype=article&item=166'>Xem thêm...<a/>"/>
    <img src="http://edu.igf.com.vn/images/slide/khaigiang04.jpg" width="730" alt="" title="Tuần học thử MIỄN PHÍ. Chúng tôi sẽ tiếp tục nhận thông tin <a href='?com=register'>đăng ký</a> của các bạn. Vui lòng <a href='?com=register'>đăng ký</a> với chúng tôi trực tiếp tại 173 Xuân Thủy, qua tư vấn tuyển sinh hoặc trên Website"/>
    <img src="http://edu.igf.com.vn/images/slide/khaigiang11.jpg" width="730" alt="" title="HÌNH ẢNH LỚP HỌC BUỔI KHAI GIẢNG TUẦN TƯ VẤN & HỌC THỬ MIỄN PHÍ.<br><a href='http://edu.igf.com.vn/index.php?com=contents&viewtype=article&item=166'>Xem thêm...<a/>"/>
    <img src="http://edu.igf.com.vn/images/slide/khaigiang12.jpg" width="730" alt="" title="HÌNH ẢNH LỚP HỌC BUỔI KHAI GIẢNG TUẦN TƯ VẤN & HỌC THỬ MIỄN PHÍ.<br><a href='http://edu.igf.com.vn/index.php?com=contents&viewtype=article&item=166'>Xem thêm...<a/>"/>
    <img src="http://edu.igf.com.vn/images/slide/khaigiang02.jpg" width="730" alt="" title="Bạn đang băn khoăn không biết học xong ra trường mình sẽ làm gì? Xin việc có khó không? Công việc có đòi hỏi nhiều kỹ năng không? Hãy để chúng tôi giúp bạn giải đáp những thắc mắc này." />
    <img src="http://edu.igf.com.vn/images/slide/khaigiang05.jpg" width="730" alt="" title="Tuần học thử MIỄN PHÍ. Chúng tôi sẽ tiếp tục nhận thông tin <a href='?com=register'>đăng ký</a> của các bạn. Vui lòng <a href='?com=register'>đăng ký</a> với chúng tôi trực tiếp tại 173 Xuân Thủy, qua tư vấn tuyển sinh hoặc trên Website"/>
</div>